// Internal link targets shared by guide pages, so related-link labels and paths stay consistent.
export const L = {
  laws: { label: "NSW taxi baby seat laws", href: "/nsw-taxi-baby-seat-laws/" },
  seatGuide: { label: "Which child seat should I request?", href: "/which-child-seat-to-request/" },
  multiple: { label: "Taxi with multiple child seats", href: "/taxi-with-multiple-child-seats-sydney/" },
  pram: { label: "Taxi with baby seat and pram", href: "/taxi-with-baby-seat-and-pram-sydney/" },
  vsRideshare: { label: "Taxi vs rideshare with a baby", href: "/taxi-vs-rideshare-with-baby-sydney/" },
  visiting: { label: "Visiting Sydney with a baby", href: "/visiting-sydney-with-a-baby/" },
  airportHub: { label: "Sydney Airport transfers with baby seats", href: "/sydney-airport-transfers-with-baby-seats/" },
  international: { label: "Sydney International Airport (T1)", href: "/sydney-international-airport-baby-seat-taxi/" },
  domestic: { label: "Sydney Domestic Airport (T2 & T3)", href: "/sydney-domestic-airport-baby-seat-taxi/" },
  airport2Seats: { label: "Airport transfer with 2 child seats", href: "/sydney-airport-transfer-with-2-child-seats/" },
  airportPram: { label: "Airport transfer with baby and pram", href: "/sydney-airport-transfer-with-baby-and-pram/" },
  airportLuggage: { label: "Airport transfer with large luggage", href: "/sydney-airport-family-transfer-large-luggage/" },
  airportHotel: { label: "Sydney Airport to hotel with baby seat", href: "/sydney-airport-to-hotel-with-baby-seat/" },
  newborn: { label: "Newborn hospital-to-home taxi", href: "/newborn-hospital-to-home-taxi-sydney/" },
  capsule: { label: "Baby capsule taxi", href: "/baby-capsule-taxi-sydney/" },
  childSeat: { label: "Child seat taxi", href: "/child-seat-taxi-sydney/" },
  areas: { label: "All Sydney areas", href: "/baby-seat-taxi-sydney-areas/" },
} as const;
